name: Test

on:
  push:
    branches: [ main ]
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches: [ main ]
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
